In [25]:
import numpy as np
import caffe

In [30]:
arr = np.zeros((3, 2, 2))

In [34]:
arr[0,:,] = 103.939
arr[1,:,] = 116.779
arr[2,:,] = 123.68
arr

array([[[ 103.939,  103.939],
        [ 103.939,  103.939]],

       [[ 116.779,  116.779],
        [ 116.779,  116.779]],

       [[ 123.68 ,  123.68 ],
        [ 123.68 ,  123.68 ]]])

In [35]:
blob = caffe.proto.caffe_pb2.BlobProto()
blob.channels, blob.height, blob.width = arr.shape
blob.data.extend(arr.astype(float).flat)
binaryproto_file = open('vgg_mean.binaryproto', 'wb' )
binaryproto_file.write(blob.SerializeToString())
binaryproto_file.close()

In [38]:
arr2 = np.zeros((2, 2, 3))

In [75]:
arr2[0,:] = 0
arr2[1,:] = 1
print(arr2)

arr2[:,:,0] = 1
arr2[:,:,1] = 2
arr2[:,:,2] = 3
arr2[0][1][2]

[[[ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]


3.0